### ISSUE TITLE
INTERNAL ERROR: cannot create temporary directory!

### ISSUE THREAD

**Issue by thanhlong9x** [intel/CPU-Manager-for-Kubernetes#277]
Hello, I am using CMK for my project. After I pin cpu for my container, I run cmk isolate with pool=shared. I get log with this format: 
[num] INTERNAL ERROR: cannot create temporary directory!
Have you met this yet ? Please share it with me? Thank you !

**Comment by DheerajDang** [comment]
it seems some issue with securitycontext configuration in the cloud.
I have faced it few days back, what you can try is to use **privileged: true** in security context.
I hope it would solve your issue. 

```yaml
securityContext:
      privileged: true
      drop:
          - all
```
